
CREATE TABLE countries (
  alpha2      CHAR(2)      PRIMARY KEY,
  alpha3      CHAR(3)      NOT NULL UNIQUE, 
  numeric3166 CHAR(3)      NOT NULL UNIQUE,
  name        VARCHAR(256) NOT NULL UNIQUE, -- hmmm, english?
  currency    CHAR(2)      FOREIGN KEY REFERENCES currencies(alpha2)
);

CREATE TABLE currencies (
  alpha3      CHAR(2)      PRIMARY KEY,
  numeric4217 CHAR(3)      NOT NULL UNIQUE,
  name        VARCHAR(256) NOT NULL UNIQUE,
  minor       NUMERIC(1)   NOT NULL,
  -- minor_name ... tbd
  -- symbol      VARCHAR(10) -- determine
);

-- CREATE TABLE flags {
--  alpha2 CHAR(2), -- fk -> countries
--  flag   VARCHAR(1024)
-- }

-- country name
-- currency name

-- COUNTRIES
INSERT INTO countries(alpha2, alpha3, numeric3166, name, currency) VALUES ('AD', 'AND','020','Andorra', 'EUR');
INSERT INTO countries(alpha2, alpha3, numeric3166, name, currency) VALUES ('AE', 'ARE','784','United Arab Emirates', 'AED');
INSERT INTO countries(alpha2, alpha3, numeric3166, name, currency) VALUES ('AF', 'AFG','004','Afghanistan', 'AFN');
INSERT INTO countries(alpha2, alpha3, numeric3166, name, currency) VALUES ('AG', 'ATG','028','Antigua and Barbuda', 'XCD');
INSERT INTO countries(alpha2, alpha3, numeric3166, name, currency) VALUES ('AI', 'AIA','660','Anguilla', 'XCD');
INSERT INTO countries(alpha2, alpha3, numeric3166, name, currency) VALUES ('AL', 'ALB','008','Albania', 'ALL');
INSERT INTO countries(alpha2, alpha3, numeric3166, name, currency) VALUES ('AM', 'ARM','051','Armenia', 'AMD');
INSERT INTO countries(alpha2, alpha3, numeric3166, name, currency) VALUES ('AO', 'AGO','024','Angola', 'AOA');
INSERT INTO countries(alpha2, alpha3, numeric3166, name, currency) VALUES ('AQ', 'ATA','010','Antarctica', '');
INSERT INTO countries(alpha2, alpha3, numeric3166, name, currency) VALUES ('AR', 'ARG','032','Argentina', 'ARS');
INSERT INTO countries(alpha2, alpha3, numeric3166, name, currency) VALUES ('AS', 'ASM','016','American Samoa', 'USD');
INSERT INTO countries(alpha2, alpha3, numeric3166, name, currency) VALUES ('AT', 'AUT','040','Austria', 'EUR');
INSERT INTO countries(alpha2, alpha3, numeric3166, name, currency) VALUES ('AU', 'AUS','036','Australia', 'AUD');
INSERT INTO countries(alpha2, alpha3, numeric3166, name, currency) VALUES ('AW', 'ABW','533','Aruba', 'AWG');
INSERT INTO countries(alpha2, alpha3, numeric3166, name, currency) VALUES ('AX', 'ALA','248','Åland Islands', 'EUR');
INSERT INTO countries(alpha2, alpha3, numeric3166, name, currency) VALUES ('AZ', 'AZE','031','Azerbaijan', 'AZN');
INSERT INTO countries(alpha2, alpha3, numeric3166, name, currency) VALUES ('BA', 'BIH','070','Bosnia and Herzegovina', 'BAM');
INSERT INTO countries(alpha2, alpha3, numeric3166, name, currency) VALUES ('BB', 'BRB','052','Barbados', 'BBD');
INSERT INTO countries(alpha2, alpha3, numeric3166, name, currency) VALUES ('BD', 'BGD','050','Bangladesh', 'BDT');
INSERT INTO countries(alpha2, alpha3, numeric3166, name, currency) VALUES ('BE', 'BEL','056','Belgium', 'EUR');
INSERT INTO countries(alpha2, alpha3, numeric3166, name, currency) VALUES ('BF', 'BFA','854','Burkina Faso', 'XOF');
INSERT INTO countries(alpha2, alpha3, numeric3166, name, currency) VALUES ('BG', 'BGR','100','Bulgaria', 'BGN');
INSERT INTO countries(alpha2, alpha3, numeric3166, name, currency) VALUES ('BH', 'BHR','048','Bahrain', 'BHD');
INSERT INTO countries(alpha2, alpha3, numeric3166, name, currency) VALUES ('BI', 'BDI','108','Burundi', 'BIF');
INSERT INTO countries(alpha2, alpha3, numeric3166, name, currency) VALUES ('BJ', 'BEN','204','Benin', 'XOF');
INSERT INTO countries(alpha2, alpha3, numeric3166, name, currency) VALUES ('BL', 'BLM','652','Saint Barthélemy', 'EUR');
INSERT INTO countries(alpha2, alpha3, numeric3166, name, currency) VALUES ('BM', 'BMU','060','Bermuda', 'BMD');
INSERT INTO countries(alpha2, alpha3, numeric3166, name, currency) VALUES ('BN', 'BRN','096','Brunei Darussalam', 'BND');
INSERT INTO countries(alpha2, alpha3, numeric3166, name, currency) VALUES ('BO', 'BOL','068','Bolivia, Plurinational State of', 'BOB');
INSERT INTO countries(alpha2, alpha3, numeric3166, name, currency) VALUES ('BQ', 'BES','535','Bonaire, Sint Eustatius and Saba', '');
INSERT INTO countries(alpha2, alpha3, numeric3166, name, currency) VALUES ('BR', 'BRA','076','Brazil', 'BRL');
INSERT INTO countries(alpha2, alpha3, numeric3166, name, currency) VALUES ('BS', 'BHS','044','Bahamas', 'BSD');
INSERT INTO countries(alpha2, alpha3, numeric3166, name, currency) VALUES ('BT', 'BTN','064','Bhutan', 'INR');
INSERT INTO countries(alpha2, alpha3, numeric3166, name, currency) VALUES ('BV', 'BVT','074','Bouvet Island', 'NOK');
INSERT INTO countries(alpha2, alpha3, numeric3166, name, currency) VALUES ('BW', 'BWA','072','Botswana', 'BWP');
INSERT INTO countries(alpha2, alpha3, numeric3166, name, currency) VALUES ('BY', 'BLR','112','Belarus', 'BYR');
INSERT INTO countries(alpha2, alpha3, numeric3166, name, currency) VALUES ('BZ', 'BLZ','084','Belize', 'BZD');
INSERT INTO countries(alpha2, alpha3, numeric3166, name, currency) VALUES ('CA', 'CAN','124','Canada', 'CAD');
INSERT INTO countries(alpha2, alpha3, numeric3166, name, currency) VALUES ('CC', 'CCK','166','Cocos (Keeling) Islands', 'AUD');
INSERT INTO countries(alpha2, alpha3, numeric3166, name, currency) VALUES ('CD', 'COD','180','Congo, the Democratic Republic of the', 'CDF');
INSERT INTO countries(alpha2, alpha3, numeric3166, name, currency) VALUES ('CF', 'CAF','140','Central African Republic', 'XAF');
INSERT INTO countries(alpha2, alpha3, numeric3166, name, currency) VALUES ('CG', 'COG','178','Congo', 'XAF');
INSERT INTO countries(alpha2, alpha3, numeric3166, name, currency) VALUES ('CH', 'CHE','756','Switzerland', 'CHF');
INSERT INTO countries(alpha2, alpha3, numeric3166, name, currency) VALUES ('CI', 'CIV','384','Côte d''Ivoire', 'XOF');
INSERT INTO countries(alpha2, alpha3, numeric3166, name, currency) VALUES ('CK', 'COK','184','Cook Islands', 'NZD');
INSERT INTO countries(alpha2, alpha3, numeric3166, name, currency) VALUES ('CL', 'CHL','152','Chile', 'CLP');
INSERT INTO countries(alpha2, alpha3, numeric3166, name, currency) VALUES ('CM', 'CMR','120','Cameroon', 'XAF');
INSERT INTO countries(alpha2, alpha3, numeric3166, name, currency) VALUES ('CN', 'CHN','156','China', 'CNY');
INSERT INTO countries(alpha2, alpha3, numeric3166, name, currency) VALUES ('CO', 'COL','170','Colombia', 'COP');
INSERT INTO countries(alpha2, alpha3, numeric3166, name, currency) VALUES ('CR', 'CRI','188','Costa Rica', 'CRC');
INSERT INTO countries(alpha2, alpha3, numeric3166, name, currency) VALUES ('CU', 'CUB','192','Cuba', 'CUP');
INSERT INTO countries(alpha2, alpha3, numeric3166, name, currency) VALUES ('CV', 'CPV','132','Cape Verde', 'CVE');
INSERT INTO countries(alpha2, alpha3, numeric3166, name, currency) VALUES ('CW', 'CUW','531','Curaçao', '');
INSERT INTO countries(alpha2, alpha3, numeric3166, name, currency) VALUES ('CX', 'CXR','162','Christmas Island', 'AUD');
INSERT INTO countries(alpha2, alpha3, numeric3166, name, currency) VALUES ('CY', 'CYP','196','Cyprus', 'EUR');
INSERT INTO countries(alpha2, alpha3, numeric3166, name, currency) VALUES ('CZ', 'CZE','203','Czech Republic', 'CZK');
INSERT INTO countries(alpha2, alpha3, numeric3166, name, currency) VALUES ('DE', 'DEU','276','Germany', 'EUR');
INSERT INTO countries(alpha2, alpha3, numeric3166, name, currency) VALUES ('DJ', 'DJI','262','Djibouti', 'DJF');
INSERT INTO countries(alpha2, alpha3, numeric3166, name, currency) VALUES ('DK', 'DNK','208','Denmark', 'DKK');
INSERT INTO countries(alpha2, alpha3, numeric3166, name, currency) VALUES ('DM', 'DMA','212','Dominica', 'XCD');
INSERT INTO countries(alpha2, alpha3, numeric3166, name, currency) VALUES ('DO', 'DOM','214','Dominican Republic', 'DOP');
INSERT INTO countries(alpha2, alpha3, numeric3166, name, currency) VALUES ('DZ', 'DZA','012','Algeria', 'DZD');
INSERT INTO countries(alpha2, alpha3, numeric3166, name, currency) VALUES ('EC', 'ECU','218','Ecuador', 'USD');
INSERT INTO countries(alpha2, alpha3, numeric3166, name, currency) VALUES ('EE', 'EST','233','Estonia', 'EUR');
INSERT INTO countries(alpha2, alpha3, numeric3166, name, currency) VALUES ('EG', 'EGY','818','Egypt', 'EGP');
INSERT INTO countries(alpha2, alpha3, numeric3166, name, currency) VALUES ('EH', 'ESH','732','Western Sahara', 'MAD');
INSERT INTO countries(alpha2, alpha3, numeric3166, name, currency) VALUES ('ER', 'ERI','232','Eritrea', 'ERN');
INSERT INTO countries(alpha2, alpha3, numeric3166, name, currency) VALUES ('ES', 'ESP','724','Spain', 'EUR');
INSERT INTO countries(alpha2, alpha3, numeric3166, name, currency) VALUES ('ET', 'ETH','231','Ethiopia', 'ETB');
INSERT INTO countries(alpha2, alpha3, numeric3166, name, currency) VALUES ('FI', 'FIN','246','Finland', 'EUR');
INSERT INTO countries(alpha2, alpha3, numeric3166, name, currency) VALUES ('FJ', 'FJI','242','Fiji', 'FJD');
INSERT INTO countries(alpha2, alpha3, numeric3166, name, currency) VALUES ('FK', 'FLK','238','Falkland Islands (Malvinas)', 'FKP');
INSERT INTO countries(alpha2, alpha3, numeric3166, name, currency) VALUES ('FM', 'FSM','583','Micronesia, Federated States of', 'USD');
INSERT INTO countries(alpha2, alpha3, numeric3166, name, currency) VALUES ('FO', 'FRO','234','Faroe Islands', 'DKK');
INSERT INTO countries(alpha2, alpha3, numeric3166, name, currency) VALUES ('FR', 'FRA','250','France', 'EUR');
INSERT INTO countries(alpha2, alpha3, numeric3166, name, currency) VALUES ('GA', 'GAB','266','Gabon', 'XAF');
INSERT INTO countries(alpha2, alpha3, numeric3166, name, currency) VALUES ('GB', 'GBR','826','United Kingdom', 'GBP');
INSERT INTO countries(alpha2, alpha3, numeric3166, name, currency) VALUES ('GD', 'GRD','308','Grenada', 'XCD');
INSERT INTO countries(alpha2, alpha3, numeric3166, name, currency) VALUES ('GE', 'GEO','268','Georgia', 'GEL');
INSERT INTO countries(alpha2, alpha3, numeric3166, name, currency) VALUES ('GF', 'GUF','254','French Guiana', 'EUR');
INSERT INTO countries(alpha2, alpha3, numeric3166, name, currency) VALUES ('GG', 'GGY','831','Guernsey', 'GBP');
INSERT INTO countries(alpha2, alpha3, numeric3166, name, currency) VALUES ('GH', 'GHA','288','Ghana', 'GHS');
INSERT INTO countries(alpha2, alpha3, numeric3166, name, currency) VALUES ('GI', 'GIB','292','Gibraltar', 'GIP');
INSERT INTO countries(alpha2, alpha3, numeric3166, name, currency) VALUES ('GL', 'GRL','304','Greenland', 'DKK');
INSERT INTO countries(alpha2, alpha3, numeric3166, name, currency) VALUES ('GM', 'GMB','270','Gambia', 'GMD');
INSERT INTO countries(alpha2, alpha3, numeric3166, name, currency) VALUES ('GN', 'GIN','324','Guinea', 'GNF');
INSERT INTO countries(alpha2, alpha3, numeric3166, name, currency) VALUES ('GP', 'GLP','312','Guadeloupe', 'EUR');
INSERT INTO countries(alpha2, alpha3, numeric3166, name, currency) VALUES ('GQ', 'GNQ','226','Equatorial Guinea', 'XAF');
INSERT INTO countries(alpha2, alpha3, numeric3166, name, currency) VALUES ('GR', 'GRC','300','Greece', 'EUR');
INSERT INTO countries(alpha2, alpha3, numeric3166, name, currency) VALUES ('GS', 'SGS','239','South Georgia and the South Sandwich Islands', 'GBP');
INSERT INTO countries(alpha2, alpha3, numeric3166, name, currency) VALUES ('GT', 'GTM','320','Guatemala', 'GTQ');
INSERT INTO countries(alpha2, alpha3, numeric3166, name, currency) VALUES ('GU', 'GUM','316','Guam', 'USD');
INSERT INTO countries(alpha2, alpha3, numeric3166, name, currency) VALUES ('GW', 'GNB','624','Guinea-Bissau', 'XOF');
INSERT INTO countries(alpha2, alpha3, numeric3166, name, currency) VALUES ('GY', 'GUY','328','Guyana', 'GYD');
INSERT INTO countries(alpha2, alpha3, numeric3166, name, currency) VALUES ('HK', 'HKG','344','Hong Kong', 'HKD');
INSERT INTO countries(alpha2, alpha3, numeric3166, name, currency) VALUES ('HM', 'HMD','334','Heard Island and McDonald Islands', 'AUD');
INSERT INTO countries(alpha2, alpha3, numeric3166, name, currency) VALUES ('HN', 'HND','340','Honduras', 'HNL');
INSERT INTO countries(alpha2, alpha3, numeric3166, name, currency) VALUES ('HR', 'HRV','191','Croatia', 'HRK');
INSERT INTO countries(alpha2, alpha3, numeric3166, name, currency) VALUES ('HT', 'HTI','332','Haiti', 'USD');
INSERT INTO countries(alpha2, alpha3, numeric3166, name, currency) VALUES ('HU', 'HUN','348','Hungary', 'HUF');
INSERT INTO countries(alpha2, alpha3, numeric3166, name, currency) VALUES ('ID', 'IDN','360','Indonesia', 'IDR');
INSERT INTO countries(alpha2, alpha3, numeric3166, name, currency) VALUES ('IE', 'IRL','372','Ireland', 'EUR');
INSERT INTO countries(alpha2, alpha3, numeric3166, name, currency) VALUES ('IL', 'ISR','376','Israel', 'ILS');
INSERT INTO countries(alpha2, alpha3, numeric3166, name, currency) VALUES ('IM', 'IMN','833','Isle of Man', 'GBP');
INSERT INTO countries(alpha2, alpha3, numeric3166, name, currency) VALUES ('IN', 'IND','356','India', 'INR');
INSERT INTO countries(alpha2, alpha3, numeric3166, name, currency) VALUES ('IO', 'IOT','086','British Indian Ocean Territory', 'GBP');
INSERT INTO countries(alpha2, alpha3, numeric3166, name, currency) VALUES ('IQ', 'IRQ','368','Iraq', 'IQD');
INSERT INTO countries(alpha2, alpha3, numeric3166, name, currency) VALUES ('IR', 'IRN','364','Iran, Islamic Republic of', 'IRR');
INSERT INTO countries(alpha2, alpha3, numeric3166, name, currency) VALUES ('IS', 'ISL','352','Iceland', 'ISK');
INSERT INTO countries(alpha2, alpha3, numeric3166, name, currency) VALUES ('IT', 'ITA','380','Italy', 'EUR');
INSERT INTO countries(alpha2, alpha3, numeric3166, name, currency) VALUES ('JE', 'JEY','832','Jersey', 'GBP');
INSERT INTO countries(alpha2, alpha3, numeric3166, name, currency) VALUES ('JM', 'JAM','388','Jamaica', 'JMD');
INSERT INTO countries(alpha2, alpha3, numeric3166, name, currency) VALUES ('JO', 'JOR','400','Jordan', 'JOD');
INSERT INTO countries(alpha2, alpha3, numeric3166, name, currency) VALUES ('JP', 'JPN','392','Japan', 'JPY');
INSERT INTO countries(alpha2, alpha3, numeric3166, name, currency) VALUES ('KE', 'KEN','404','Kenya', 'KES');
INSERT INTO countries(alpha2, alpha3, numeric3166, name, currency) VALUES ('KG', 'KGZ','417','Kyrgyzstan', 'KGS');
INSERT INTO countries(alpha2, alpha3, numeric3166, name, currency) VALUES ('KH', 'KHM','116','Cambodia', 'KHR');
INSERT INTO countries(alpha2, alpha3, numeric3166, name, currency) VALUES ('KI', 'KIR','296','Kiribati', 'AUD');
INSERT INTO countries(alpha2, alpha3, numeric3166, name, currency) VALUES ('KM', 'COM','174','Comoros', 'KMF');
INSERT INTO countries(alpha2, alpha3, numeric3166, name, currency) VALUES ('KN', 'KNA','659','Saint Kitts and Nevis', 'XCD');
INSERT INTO countries(alpha2, alpha3, numeric3166, name, currency) VALUES ('KP', 'PRK','408','Korea, Democratic People''s Republic of', 'KPW');
INSERT INTO countries(alpha2, alpha3, numeric3166, name, currency) VALUES ('KR', 'KOR','410','Korea, Republic of', 'KRW');
INSERT INTO countries(alpha2, alpha3, numeric3166, name, currency) VALUES ('KW', 'KWT','414','Kuwait', 'KWD');
INSERT INTO countries(alpha2, alpha3, numeric3166, name, currency) VALUES ('KY', 'CYM','136','Cayman Islands', 'KYD');
INSERT INTO countries(alpha2, alpha3, numeric3166, name, currency) VALUES ('KZ', 'KAZ','398','Kazakhstan', 'KZT');
INSERT INTO countries(alpha2, alpha3, numeric3166, name, currency) VALUES ('LA', 'LAO','418','Lao People''s Democratic Republic', 'LAK');
INSERT INTO countries(alpha2, alpha3, numeric3166, name, currency) VALUES ('LB', 'LBN','422','Lebanon', 'LBP');
INSERT INTO countries(alpha2, alpha3, numeric3166, name, currency) VALUES ('LC', 'LCA','662','Saint Lucia', 'XCD');
INSERT INTO countries(alpha2, alpha3, numeric3166, name, currency) VALUES ('LI', 'LIE','438','Liechtenstein', 'CHF');
INSERT INTO countries(alpha2, alpha3, numeric3166, name, currency) VALUES ('LK', 'LKA','144','Sri Lanka', 'LKR');
INSERT INTO countries(alpha2, alpha3, numeric3166, name, currency) VALUES ('LR', 'LBR','430','Liberia', 'LRD');
INSERT INTO countries(alpha2, alpha3, numeric3166, name, currency) VALUES ('LS', 'LSO','426','Lesotho', 'LSL');
INSERT INTO countries(alpha2, alpha3, numeric3166, name, currency) VALUES ('LT', 'LTU','440','Lithuania', 'LTL');
INSERT INTO countries(alpha2, alpha3, numeric3166, name, currency) VALUES ('LU', 'LUX','442','Luxembourg', 'EUR');
INSERT INTO countries(alpha2, alpha3, numeric3166, name, currency) VALUES ('LV', 'LVA','428','Latvia', 'LVL');
INSERT INTO countries(alpha2, alpha3, numeric3166, name, currency) VALUES ('LY', 'LBY','434','Libya', 'LYD');
INSERT INTO countries(alpha2, alpha3, numeric3166, name, currency) VALUES ('MA', 'MAR','504','Morocco', 'MAD');
INSERT INTO countries(alpha2, alpha3, numeric3166, name, currency) VALUES ('MC', 'MCO','492','Monaco', 'EUR');
INSERT INTO countries(alpha2, alpha3, numeric3166, name, currency) VALUES ('MD', 'MDA','498','Moldova, Republic of', 'MDL');
INSERT INTO countries(alpha2, alpha3, numeric3166, name, currency) VALUES ('ME', 'MNE','499','Montenegro', 'EUR');
INSERT INTO countries(alpha2, alpha3, numeric3166, name, currency) VALUES ('MF', 'MAF','663','Saint Martin (French part)', 'EUR');
INSERT INTO countries(alpha2, alpha3, numeric3166, name, currency) VALUES ('MG', 'MDG','450','Madagascar', 'MGA');
INSERT INTO countries(alpha2, alpha3, numeric3166, name, currency) VALUES ('MH', 'MHL','584','Marshall Islands', 'USD');
INSERT INTO countries(alpha2, alpha3, numeric3166, name, currency) VALUES ('MK', 'MKD','807','Macedonia, The Former Yugoslav Republic of', 'MKD');
INSERT INTO countries(alpha2, alpha3, numeric3166, name, currency) VALUES ('ML', 'MLI','466','Mali', 'XOF');
INSERT INTO countries(alpha2, alpha3, numeric3166, name, currency) VALUES ('MM', 'MMR','104','Myanmar', 'MMK');
INSERT INTO countries(alpha2, alpha3, numeric3166, name, currency) VALUES ('MN', 'MNG','496','Mongolia', 'MNT');
INSERT INTO countries(alpha2, alpha3, numeric3166, name, currency) VALUES ('MO', 'MAC','446','Macao', 'MOP');
INSERT INTO countries(alpha2, alpha3, numeric3166, name, currency) VALUES ('MP', 'MNP','580','Northern Mariana Islands', 'USD');
INSERT INTO countries(alpha2, alpha3, numeric3166, name, currency) VALUES ('MQ', 'MTQ','474','Martinique', 'EUR');
INSERT INTO countries(alpha2, alpha3, numeric3166, name, currency) VALUES ('MR', 'MRT','478','Mauritania', 'MRO');
INSERT INTO countries(alpha2, alpha3, numeric3166, name, currency) VALUES ('MS', 'MSR','500','Montserrat', 'XCD');
INSERT INTO countries(alpha2, alpha3, numeric3166, name, currency) VALUES ('MT', 'MLT','470','Malta', 'EUR');
INSERT INTO countries(alpha2, alpha3, numeric3166, name, currency) VALUES ('MU', 'MUS','480','Mauritius', 'MUR');
INSERT INTO countries(alpha2, alpha3, numeric3166, name, currency) VALUES ('MV', 'MDV','462','Maldives', 'MVR');
INSERT INTO countries(alpha2, alpha3, numeric3166, name, currency) VALUES ('MW', 'MWI','454','Malawi', 'MWK');
INSERT INTO countries(alpha2, alpha3, numeric3166, name, currency) VALUES ('MX', 'MEX','484','Mexico', 'MXN');
INSERT INTO countries(alpha2, alpha3, numeric3166, name, currency) VALUES ('MY', 'MYS','458','Malaysia', 'MYR');
INSERT INTO countries(alpha2, alpha3, numeric3166, name, currency) VALUES ('MZ', 'MOZ','508','Mozambique', 'MZN');
INSERT INTO countries(alpha2, alpha3, numeric3166, name, currency) VALUES ('NA', 'NAM','516','Namibia', 'NAD');
INSERT INTO countries(alpha2, alpha3, numeric3166, name, currency) VALUES ('NC', 'NCL','540','New Caledonia', 'XPF');
INSERT INTO countries(alpha2, alpha3, numeric3166, name, currency) VALUES ('NE', 'NER','562','Niger', 'XOF');
INSERT INTO countries(alpha2, alpha3, numeric3166, name, currency) VALUES ('NF', 'NFK','574','Norfolk Island', 'AUD');
INSERT INTO countries(alpha2, alpha3, numeric3166, name, currency) VALUES ('NG', 'NGA','566','Nigeria', 'NGN');
INSERT INTO countries(alpha2, alpha3, numeric3166, name, currency) VALUES ('NI', 'NIC','558','Nicaragua', 'NIO');
INSERT INTO countries(alpha2, alpha3, numeric3166, name, currency) VALUES ('NL', 'NLD','528','Netherlands', 'EUR');
INSERT INTO countries(alpha2, alpha3, numeric3166, name, currency) VALUES ('NO', 'NOR','578','Norway', 'NOK');
INSERT INTO countries(alpha2, alpha3, numeric3166, name, currency) VALUES ('NP', 'NPL','524','Nepal', 'NPR');
INSERT INTO countries(alpha2, alpha3, numeric3166, name, currency) VALUES ('NR', 'NRU','520','Nauru', 'AUD');
INSERT INTO countries(alpha2, alpha3, numeric3166, name, currency) VALUES ('NU', 'NIU','570','Niue', 'NZD');
INSERT INTO countries(alpha2, alpha3, numeric3166, name, currency) VALUES ('NZ', 'NZL','554','New Zealand', 'NZD');
INSERT INTO countries(alpha2, alpha3, numeric3166, name, currency) VALUES ('OM', 'OMN','512','Oman', 'OMR');
INSERT INTO countries(alpha2, alpha3, numeric3166, name, currency) VALUES ('PA', 'PAN','591','Panama', 'USD');
INSERT INTO countries(alpha2, alpha3, numeric3166, name, currency) VALUES ('PE', 'PER','604','Peru', 'PEN');
INSERT INTO countries(alpha2, alpha3, numeric3166, name, currency) VALUES ('PF', 'PYF','258','French Polynesia', 'XPF');
INSERT INTO countries(alpha2, alpha3, numeric3166, name, currency) VALUES ('PG', 'PNG','598','Papua New Guinea', 'PGK');
INSERT INTO countries(alpha2, alpha3, numeric3166, name, currency) VALUES ('PH', 'PHL','608','Philippines', 'PHP');
INSERT INTO countries(alpha2, alpha3, numeric3166, name, currency) VALUES ('PK', 'PAK','586','Pakistan', 'PKR');
INSERT INTO countries(alpha2, alpha3, numeric3166, name, currency) VALUES ('PL', 'POL','616','Poland', 'PLN');
INSERT INTO countries(alpha2, alpha3, numeric3166, name, currency) VALUES ('PM', 'SPM','666','Saint Pierre and Miquelon', 'EUR');
INSERT INTO countries(alpha2, alpha3, numeric3166, name, currency) VALUES ('PN', 'PCN','612','Pitcairn', 'NZD');
INSERT INTO countries(alpha2, alpha3, numeric3166, name, currency) VALUES ('PR', 'PRI','630','Puerto Rico', 'USD');
INSERT INTO countries(alpha2, alpha3, numeric3166, name, currency) VALUES ('PS', 'PSE','275','Palestine, State of', 'ILS');
INSERT INTO countries(alpha2, alpha3, numeric3166, name, currency) VALUES ('PT', 'PRT','620','Portugal', 'EUR');
INSERT INTO countries(alpha2, alpha3, numeric3166, name, currency) VALUES ('PW', 'PLW','585','Palau', 'USD');
INSERT INTO countries(alpha2, alpha3, numeric3166, name, currency) VALUES ('PY', 'PRY','600','Paraguay', 'PYG');
INSERT INTO countries(alpha2, alpha3, numeric3166, name, currency) VALUES ('QA', 'QAT','634','Qatar', 'QAR');
INSERT INTO countries(alpha2, alpha3, numeric3166, name, currency) VALUES ('RE', 'REU','638','Réunion', 'EUR');
INSERT INTO countries(alpha2, alpha3, numeric3166, name, currency) VALUES ('RO', 'ROU','642','Romania', 'RON');
INSERT INTO countries(alpha2, alpha3, numeric3166, name, currency) VALUES ('RS', 'SRB','688','Serbia', 'RSD');
INSERT INTO countries(alpha2, alpha3, numeric3166, name, currency) VALUES ('RU', 'RUS','643','Russian Federation', 'RUB');
INSERT INTO countries(alpha2, alpha3, numeric3166, name, currency) VALUES ('RW', 'RWA','646','Rwanda', 'RWF');
INSERT INTO countries(alpha2, alpha3, numeric3166, name, currency) VALUES ('SA', 'SAU','682','Saudi Arabia', 'SAR');
INSERT INTO countries(alpha2, alpha3, numeric3166, name, currency) VALUES ('SB', 'SLB','090','Solomon Islands', 'SBD');
INSERT INTO countries(alpha2, alpha3, numeric3166, name, currency) VALUES ('SC', 'SYC','690','Seychelles', 'SCR');
INSERT INTO countries(alpha2, alpha3, numeric3166, name, currency) VALUES ('SD', 'SDN','729','Sudan', 'SDG');
INSERT INTO countries(alpha2, alpha3, numeric3166, name, currency) VALUES ('SE', 'SWE','752','Sweden', 'SEK');
INSERT INTO countries(alpha2, alpha3, numeric3166, name, currency) VALUES ('SG', 'SGP','702','Singapore', 'SGD');
INSERT INTO countries(alpha2, alpha3, numeric3166, name, currency) VALUES ('SH', 'SHN','654','Saint Helena, Ascension and Tristan da Cunha', 'SHP');
INSERT INTO countries(alpha2, alpha3, numeric3166, name, currency) VALUES ('SI', 'SVN','705','Slovenia', 'EUR');
INSERT INTO countries(alpha2, alpha3, numeric3166, name, currency) VALUES ('SJ', 'SJM','744','Svalbard and Jan Mayen', 'NOK');
INSERT INTO countries(alpha2, alpha3, numeric3166, name, currency) VALUES ('SK', 'SVK','703','Slovakia', 'EUR');
INSERT INTO countries(alpha2, alpha3, numeric3166, name, currency) VALUES ('SL', 'SLE','694','Sierra Leone', 'SLL');
INSERT INTO countries(alpha2, alpha3, numeric3166, name, currency) VALUES ('SM', 'SMR','674','San Marino', 'EUR');
INSERT INTO countries(alpha2, alpha3, numeric3166, name, currency) VALUES ('SN', 'SEN','686','Senegal', 'XOF');
INSERT INTO countries(alpha2, alpha3, numeric3166, name, currency) VALUES ('SO', 'SOM','706','Somalia', 'SOS');
INSERT INTO countries(alpha2, alpha3, numeric3166, name, currency) VALUES ('SR', 'SUR','740','Suriname', 'SRD');
INSERT INTO countries(alpha2, alpha3, numeric3166, name, currency) VALUES ('SS', 'SSD','728','South Sudan', 'SSP');
INSERT INTO countries(alpha2, alpha3, numeric3166, name, currency) VALUES ('ST', 'STP','678','Sao Tome and Principe', 'STD');
INSERT INTO countries(alpha2, alpha3, numeric3166, name, currency) VALUES ('SV', 'SLV','222','El Salvador', 'USD');
INSERT INTO countries(alpha2, alpha3, numeric3166, name, currency) VALUES ('SX', 'SXM','534','Sint Maarten (Dutch part)', '');
INSERT INTO countries(alpha2, alpha3, numeric3166, name, currency) VALUES ('SY', 'SYR','760','Syrian Arab Republic', 'SYP');
INSERT INTO countries(alpha2, alpha3, numeric3166, name, currency) VALUES ('SZ', 'SWZ','748','Swaziland', 'SZL');
INSERT INTO countries(alpha2, alpha3, numeric3166, name, currency) VALUES ('TC', 'TCA','796','Turks and Caicos Islands', 'USD');
INSERT INTO countries(alpha2, alpha3, numeric3166, name, currency) VALUES ('TD', 'TCD','148','Chad', 'XAF');
INSERT INTO countries(alpha2, alpha3, numeric3166, name, currency) VALUES ('TF', 'ATF','260','French Southern Territories', 'EUR');
INSERT INTO countries(alpha2, alpha3, numeric3166, name, currency) VALUES ('TG', 'TGO','768','Togo', 'XOF');
INSERT INTO countries(alpha2, alpha3, numeric3166, name, currency) VALUES ('TH', 'THA','764','Thailand', 'THB');
INSERT INTO countries(alpha2, alpha3, numeric3166, name, currency) VALUES ('TJ', 'TJK','762','Tajikistan', 'TJS');
INSERT INTO countries(alpha2, alpha3, numeric3166, name, currency) VALUES ('TK', 'TKL','772','Tokelau', 'NZD');
INSERT INTO countries(alpha2, alpha3, numeric3166, name, currency) VALUES ('TL', 'TLS','626','Timor-Leste', 'USD');
INSERT INTO countries(alpha2, alpha3, numeric3166, name, currency) VALUES ('TM', 'TKM','795','Turkmenistan', 'TMT');
INSERT INTO countries(alpha2, alpha3, numeric3166, name, currency) VALUES ('TN', 'TUN','788','Tunisia', 'TND');
INSERT INTO countries(alpha2, alpha3, numeric3166, name, currency) VALUES ('TO', 'TON','776','Tonga', 'TOP');
INSERT INTO countries(alpha2, alpha3, numeric3166, name, currency) VALUES ('TR', 'TUR','792','Turkey', 'TRY');
INSERT INTO countries(alpha2, alpha3, numeric3166, name, currency) VALUES ('TT', 'TTO','780','Trinidad and Tobago', 'TTD');
INSERT INTO countries(alpha2, alpha3, numeric3166, name, currency) VALUES ('TV', 'TUV','798','Tuvalu', 'AUD');
INSERT INTO countries(alpha2, alpha3, numeric3166, name, currency) VALUES ('TW', 'TWN','158','Taiwan, Province of China', 'TWD');
INSERT INTO countries(alpha2, alpha3, numeric3166, name, currency) VALUES ('TZ', 'TZA','834','Tanzania, United Republic of', 'TZS');
INSERT INTO countries(alpha2, alpha3, numeric3166, name, currency) VALUES ('UA', 'UKR','804','Ukraine', 'UAH');
INSERT INTO countries(alpha2, alpha3, numeric3166, name, currency) VALUES ('UG', 'UGA','800','Uganda', 'UGX');
INSERT INTO countries(alpha2, alpha3, numeric3166, name, currency) VALUES ('UM', 'UMI','581','United States Minor Outlying Islands', 'USD');
INSERT INTO countries(alpha2, alpha3, numeric3166, name, currency) VALUES ('US', 'USA','840','United States', 'USD');
INSERT INTO countries(alpha2, alpha3, numeric3166, name, currency) VALUES ('UY', 'URY','858','Uruguay', 'UYU');
INSERT INTO countries(alpha2, alpha3, numeric3166, name, currency) VALUES ('UZ', 'UZB','860','Uzbekistan', 'UZS');
INSERT INTO countries(alpha2, alpha3, numeric3166, name, currency) VALUES ('VA', 'VAT','336','Holy See (Vatican City State)', 'EUR');
INSERT INTO countries(alpha2, alpha3, numeric3166, name, currency) VALUES ('VC', 'VCT','670','Saint Vincent and the Grenadines', 'XCD');
INSERT INTO countries(alpha2, alpha3, numeric3166, name, currency) VALUES ('VE', 'VEN','862','Venezuela, Bolivarian Republic of', 'VEF');
INSERT INTO countries(alpha2, alpha3, numeric3166, name, currency) VALUES ('VG', 'VGB','092','Virgin Islands, British', 'USD');
INSERT INTO countries(alpha2, alpha3, numeric3166, name, currency) VALUES ('VI', 'VIR','850','Virgin Islands, U.S.', 'USD');
INSERT INTO countries(alpha2, alpha3, numeric3166, name, currency) VALUES ('VN', 'VNM','704','Viet Nam', 'VND');
INSERT INTO countries(alpha2, alpha3, numeric3166, name, currency) VALUES ('VU', 'VUT','548','Vanuatu', 'VUV');
INSERT INTO countries(alpha2, alpha3, numeric3166, name, currency) VALUES ('WF', 'WLF','876','Wallis and Futuna', 'XPF');
INSERT INTO countries(alpha2, alpha3, numeric3166, name, currency) VALUES ('WS', 'WSM','882','Samoa', 'WST');
INSERT INTO countries(alpha2, alpha3, numeric3166, name, currency) VALUES ('YE', 'YEM','887','Yemen', 'YER');
INSERT INTO countries(alpha2, alpha3, numeric3166, name, currency) VALUES ('YT', 'MYT','175','Mayotte', 'EUR');
INSERT INTO countries(alpha2, alpha3, numeric3166, name, currency) VALUES ('ZA', 'ZAF','710','South Africa', 'ZAR');
INSERT INTO countries(alpha2, alpha3, numeric3166, name, currency) VALUES ('ZM', 'ZMB','894','Zambia', 'ZMK');
INSERT INTO countries(alpha2, alpha3, numeric3166, name, currency) VALUES ('ZW', 'ZWE','716','Zimbabwe', 'USD');

-- CURRENCIES
INSERT INTO currencies(alpha3, numeric4217, name, symbol, minor) VALUES ('AED', '784','UAE Dirham','2');
INSERT INTO currencies(alpha3, numeric4217, name, symbol, minor) VALUES ('AFN', '971','Afghani','2');
INSERT INTO currencies(alpha3, numeric4217, name, symbol, minor) VALUES ('ALL', '008','Lek','2');
INSERT INTO currencies(alpha3, numeric4217, name, symbol, minor) VALUES ('AMD', '051','Armenian Dram','2');
INSERT INTO currencies(alpha3, numeric4217, name, symbol, minor) VALUES ('ANG', '532','Netherlands Antillean Guilder','2');
INSERT INTO currencies(alpha3, numeric4217, name, symbol, minor) VALUES ('AOA', '973','Kwanza','2');
INSERT INTO currencies(alpha3, numeric4217, name, symbol, minor) VALUES ('ARS', '032','Argentine Peso','2');
INSERT INTO currencies(alpha3, numeric4217, name, symbol, minor) VALUES ('AUD', '036','Australian Dollar','2');
INSERT INTO currencies(alpha3, numeric4217, name, symbol, minor) VALUES ('AWG', '533','Aruban Florin','2');
INSERT INTO currencies(alpha3, numeric4217, name, symbol, minor) VALUES ('AZN', '944','Azerbaijanian Manat','2');
INSERT INTO currencies(alpha3, numeric4217, name, symbol, minor) VALUES ('BAM', '977','Convertible Mark','2');
INSERT INTO currencies(alpha3, numeric4217, name, symbol, minor) VALUES ('BBD', '052','Barbados Dollar','2');
INSERT INTO currencies(alpha3, numeric4217, name, symbol, minor) VALUES ('BDT', '050','Taka','2');
INSERT INTO currencies(alpha3, numeric4217, name, symbol, minor) VALUES ('BGN', '975','Bulgarian Lev','2');
INSERT INTO currencies(alpha3, numeric4217, name, symbol, minor) VALUES ('BHD', '048','Bahraini Dinar','3');
INSERT INTO currencies(alpha3, numeric4217, name, symbol, minor) VALUES ('BIF', '108','Burundi Franc','0');
INSERT INTO currencies(alpha3, numeric4217, name, symbol, minor) VALUES ('BMD', '060','Bermudian Dollar','2');
INSERT INTO currencies(alpha3, numeric4217, name, symbol, minor) VALUES ('BND', '096','Brunei Dollar','2');
INSERT INTO currencies(alpha3, numeric4217, name, symbol, minor) VALUES ('BOB', '068','Boliviano','2');
INSERT INTO currencies(alpha3, numeric4217, name, symbol, minor) VALUES ('BOV', '984','Mvdol','2');
INSERT INTO currencies(alpha3, numeric4217, name, symbol, minor) VALUES ('BRL', '986','Brazilian Real','2');
INSERT INTO currencies(alpha3, numeric4217, name, symbol, minor) VALUES ('BSD', '044','Bahamian Dollar','2');
INSERT INTO currencies(alpha3, numeric4217, name, symbol, minor) VALUES ('BTN', '064','Ngultrum','2');
INSERT INTO currencies(alpha3, numeric4217, name, symbol, minor) VALUES ('BWP', '072','Pula','2');
INSERT INTO currencies(alpha3, numeric4217, name, symbol, minor) VALUES ('BYR', '974','Belarussian Ruble','0');
INSERT INTO currencies(alpha3, numeric4217, name, symbol, minor) VALUES ('BZD', '084','Belize Dollar','2');
INSERT INTO currencies(alpha3, numeric4217, name, symbol, minor) VALUES ('CAD', '124','Canadian Dollar','2');
INSERT INTO currencies(alpha3, numeric4217, name, symbol, minor) VALUES ('CDF', '976','Congolese Franc','2');
INSERT INTO currencies(alpha3, numeric4217, name, symbol, minor) VALUES ('CHE', '947','WIR Euro','2');
INSERT INTO currencies(alpha3, numeric4217, name, symbol, minor) VALUES ('CHF', '756','Swiss Franc','2');
INSERT INTO currencies(alpha3, numeric4217, name, symbol, minor) VALUES ('CHW', '948','WIR Franc','2');
INSERT INTO currencies(alpha3, numeric4217, name, symbol, minor) VALUES ('CLF', '990','Unidades de fomento','0');
INSERT INTO currencies(alpha3, numeric4217, name, symbol, minor) VALUES ('CLP', '152','Chilean Peso','0');
INSERT INTO currencies(alpha3, numeric4217, name, symbol, minor) VALUES ('CNY', '156','Yuan Renminbi','2');
INSERT INTO currencies(alpha3, numeric4217, name, symbol, minor) VALUES ('COP', '170','Colombian Peso','2');
INSERT INTO currencies(alpha3, numeric4217, name, symbol, minor) VALUES ('COU', '970','Unidad de Valor Real','2');
INSERT INTO currencies(alpha3, numeric4217, name, symbol, minor) VALUES ('CRC', '188','Costa Rican Colon','2');
INSERT INTO currencies(alpha3, numeric4217, name, symbol, minor) VALUES ('CUC', '931','Peso Convertible','2');
INSERT INTO currencies(alpha3, numeric4217, name, symbol, minor) VALUES ('CUP', '192','Cuban Peso','2');
INSERT INTO currencies(alpha3, numeric4217, name, symbol, minor) VALUES ('CVE', '132','Cape Verde Escudo','2');
INSERT INTO currencies(alpha3, numeric4217, name, symbol, minor) VALUES ('CZK', '203','Czech Koruna','2');
INSERT INTO currencies(alpha3, numeric4217, name, symbol, minor) VALUES ('DJF', '262','Djibouti Franc','0');
INSERT INTO currencies(alpha3, numeric4217, name, symbol, minor) VALUES ('DKK', '208','Danish Krone','2');
INSERT INTO currencies(alpha3, numeric4217, name, symbol, minor) VALUES ('DOP', '214','Dominican Peso','2');
INSERT INTO currencies(alpha3, numeric4217, name, symbol, minor) VALUES ('DZD', '012','Algerian Dinar','2');
INSERT INTO currencies(alpha3, numeric4217, name, symbol, minor) VALUES ('EGP', '818','Egyptian Pound','2');
INSERT INTO currencies(alpha3, numeric4217, name, symbol, minor) VALUES ('ERN', '232','Nakfa','2');
INSERT INTO currencies(alpha3, numeric4217, name, symbol, minor) VALUES ('ETB', '230','Ethiopian Birr','2');
INSERT INTO currencies(alpha3, numeric4217, name, symbol, minor) VALUES ('EUR', '978','Euro','2');
INSERT INTO currencies(alpha3, numeric4217, name, symbol, minor) VALUES ('FJD', '242','Fiji Dollar','2');
INSERT INTO currencies(alpha3, numeric4217, name, symbol, minor) VALUES ('FKP', '238','Falkland Islands Pound','2');
INSERT INTO currencies(alpha3, numeric4217, name, symbol, minor) VALUES ('GBP', '826','Pound Sterling','2');
INSERT INTO currencies(alpha3, numeric4217, name, symbol, minor) VALUES ('GEL', '981','Lari','2');
INSERT INTO currencies(alpha3, numeric4217, name, symbol, minor) VALUES ('GHS', '936','Ghana Cedi','2');
INSERT INTO currencies(alpha3, numeric4217, name, symbol, minor) VALUES ('GIP', '292','Gibraltar Pound','2');
INSERT INTO currencies(alpha3, numeric4217, name, symbol, minor) VALUES ('GMD', '270','Dalasi','2');
INSERT INTO currencies(alpha3, numeric4217, name, symbol, minor) VALUES ('GNF', '324','Guinea Franc','0');
INSERT INTO currencies(alpha3, numeric4217, name, symbol, minor) VALUES ('GTQ', '320','Quetzal','2');
INSERT INTO currencies(alpha3, numeric4217, name, symbol, minor) VALUES ('GYD', '328','Guyana Dollar','2');
INSERT INTO currencies(alpha3, numeric4217, name, symbol, minor) VALUES ('HKD', '344','Hong Kong Dollar','2');
INSERT INTO currencies(alpha3, numeric4217, name, symbol, minor) VALUES ('HNL', '340','Lempira','2');
INSERT INTO currencies(alpha3, numeric4217, name, symbol, minor) VALUES ('HRK', '191','Croatian Kuna','2');
INSERT INTO currencies(alpha3, numeric4217, name, symbol, minor) VALUES ('HTG', '332','Gourde','2');
INSERT INTO currencies(alpha3, numeric4217, name, symbol, minor) VALUES ('HUF', '348','Forint','2');
INSERT INTO currencies(alpha3, numeric4217, name, symbol, minor) VALUES ('IDR', '360','Rupiah','2');
INSERT INTO currencies(alpha3, numeric4217, name, symbol, minor) VALUES ('ILS', '376','New Israeli Sheqel','2');
INSERT INTO currencies(alpha3, numeric4217, name, symbol, minor) VALUES ('INR', '356','Indian Rupee','2');
INSERT INTO currencies(alpha3, numeric4217, name, symbol, minor) VALUES ('IQD', '368','Iraqi Dinar','3');
INSERT INTO currencies(alpha3, numeric4217, name, symbol, minor) VALUES ('IRR', '364','Iranian Rial','2');
INSERT INTO currencies(alpha3, numeric4217, name, symbol, minor) VALUES ('ISK', '352','Iceland Krona','0');
INSERT INTO currencies(alpha3, numeric4217, name, symbol, minor) VALUES ('JMD', '388','Jamaican Dollar','2');
INSERT INTO currencies(alpha3, numeric4217, name, symbol, minor) VALUES ('JOD', '400','Jordanian Dinar','3');
INSERT INTO currencies(alpha3, numeric4217, name, symbol, minor) VALUES ('JPY', '392','Yen','0');
INSERT INTO currencies(alpha3, numeric4217, name, symbol, minor) VALUES ('KES', '404','Kenyan Shilling','2');
INSERT INTO currencies(alpha3, numeric4217, name, symbol, minor) VALUES ('KGS', '417','Som','2');
INSERT INTO currencies(alpha3, numeric4217, name, symbol, minor) VALUES ('KHR', '116','Riel','2');
INSERT INTO currencies(alpha3, numeric4217, name, symbol, minor) VALUES ('KMF', '174','Comoro Franc','0');
INSERT INTO currencies(alpha3, numeric4217, name, symbol, minor) VALUES ('KPW', '408','North Korean Won','2');
INSERT INTO currencies(alpha3, numeric4217, name, symbol, minor) VALUES ('KRW', '410','Won','0');
INSERT INTO currencies(alpha3, numeric4217, name, symbol, minor) VALUES ('KWD', '414','Kuwaiti Dinar','3');
INSERT INTO currencies(alpha3, numeric4217, name, symbol, minor) VALUES ('KYD', '136','Cayman Islands Dollar','2');
INSERT INTO currencies(alpha3, numeric4217, name, symbol, minor) VALUES ('KZT', '398','Tenge','2');
INSERT INTO currencies(alpha3, numeric4217, name, symbol, minor) VALUES ('LAK', '418','Kip','2');
INSERT INTO currencies(alpha3, numeric4217, name, symbol, minor) VALUES ('LBP', '422','Lebanese Pound','2');
INSERT INTO currencies(alpha3, numeric4217, name, symbol, minor) VALUES ('LKR', '144','Sri Lanka Rupee','2');
INSERT INTO currencies(alpha3, numeric4217, name, symbol, minor) VALUES ('LRD', '430','Liberian Dollar','2');
INSERT INTO currencies(alpha3, numeric4217, name, symbol, minor) VALUES ('LSL', '426','Loti','2');
INSERT INTO currencies(alpha3, numeric4217, name, symbol, minor) VALUES ('LTL', '440','Lithuanian Litas','2');
INSERT INTO currencies(alpha3, numeric4217, name, symbol, minor) VALUES ('LVL', '428','Latvian Lats','2');
INSERT INTO currencies(alpha3, numeric4217, name, symbol, minor) VALUES ('LYD', '434','Libyan Dinar','3');
INSERT INTO currencies(alpha3, numeric4217, name, symbol, minor) VALUES ('MAD', '504','Moroccan Dirham','2');
INSERT INTO currencies(alpha3, numeric4217, name, symbol, minor) VALUES ('MDL', '498','Moldovan Leu','2');
INSERT INTO currencies(alpha3, numeric4217, name, symbol, minor) VALUES ('MGA', '969','Malagasy Ariary','2');
INSERT INTO currencies(alpha3, numeric4217, name, symbol, minor) VALUES ('MKD', '807','Denar','2');
INSERT INTO currencies(alpha3, numeric4217, name, symbol, minor) VALUES ('MMK', '104','Kyat','2');
INSERT INTO currencies(alpha3, numeric4217, name, symbol, minor) VALUES ('MNT', '496','Tugrik','2');
INSERT INTO currencies(alpha3, numeric4217, name, symbol, minor) VALUES ('MOP', '446','Pataca','2');
INSERT INTO currencies(alpha3, numeric4217, name, symbol, minor) VALUES ('MRO', '478','Ouguiya','2');
INSERT INTO currencies(alpha3, numeric4217, name, symbol, minor) VALUES ('MUR', '480','Mauritius Rupee','2');
INSERT INTO currencies(alpha3, numeric4217, name, symbol, minor) VALUES ('MVR', '462','Rufiyaa','2');
INSERT INTO currencies(alpha3, numeric4217, name, symbol, minor) VALUES ('MWK', '454','Kwacha','2');
INSERT INTO currencies(alpha3, numeric4217, name, symbol, minor) VALUES ('MXN', '484','Mexican Peso','2');
INSERT INTO currencies(alpha3, numeric4217, name, symbol, minor) VALUES ('MXV', '979','Mexican Unidad de Inversion (UDI)','2');
INSERT INTO currencies(alpha3, numeric4217, name, symbol, minor) VALUES ('MYR', '458','Malaysian Ringgit','2');
INSERT INTO currencies(alpha3, numeric4217, name, symbol, minor) VALUES ('MZN', '943','Mozambique Metical','2');
INSERT INTO currencies(alpha3, numeric4217, name, symbol, minor) VALUES ('NAD', '516','Namibia Dollar','2');
INSERT INTO currencies(alpha3, numeric4217, name, symbol, minor) VALUES ('NGN', '566','Naira','2');
INSERT INTO currencies(alpha3, numeric4217, name, symbol, minor) VALUES ('NIO', '558','Cordoba Oro','2');
INSERT INTO currencies(alpha3, numeric4217, name, symbol, minor) VALUES ('NOK', '578','Norwegian Krone','2');
INSERT INTO currencies(alpha3, numeric4217, name, symbol, minor) VALUES ('NPR', '524','Nepalese Rupee','2');
INSERT INTO currencies(alpha3, numeric4217, name, symbol, minor) VALUES ('NZD', '554','New Zealand Dollar','2');
INSERT INTO currencies(alpha3, numeric4217, name, symbol, minor) VALUES ('OMR', '512','Rial Omani','3');
INSERT INTO currencies(alpha3, numeric4217, name, symbol, minor) VALUES ('PAB', '590','Balboa','2');
INSERT INTO currencies(alpha3, numeric4217, name, symbol, minor) VALUES ('PEN', '604','Nuevo Sol','2');
INSERT INTO currencies(alpha3, numeric4217, name, symbol, minor) VALUES ('PGK', '598','Kina','2');
INSERT INTO currencies(alpha3, numeric4217, name, symbol, minor) VALUES ('PHP', '608','Philippine Peso','2');
INSERT INTO currencies(alpha3, numeric4217, name, symbol, minor) VALUES ('PKR', '586','Pakistan Rupee','2');
INSERT INTO currencies(alpha3, numeric4217, name, symbol, minor) VALUES ('PLN', '985','Zloty','2');
INSERT INTO currencies(alpha3, numeric4217, name, symbol, minor) VALUES ('PYG', '600','Guarani','0');
INSERT INTO currencies(alpha3, numeric4217, name, symbol, minor) VALUES ('QAR', '634','Qatari Rial','2');
INSERT INTO currencies(alpha3, numeric4217, name, symbol, minor) VALUES ('RON', '946','New Romanian Leu','2');
INSERT INTO currencies(alpha3, numeric4217, name, symbol, minor) VALUES ('RSD', '941','Serbian Dinar','2');
INSERT INTO currencies(alpha3, numeric4217, name, symbol, minor) VALUES ('RUB', '643','Russian Ruble','2');
INSERT INTO currencies(alpha3, numeric4217, name, symbol, minor) VALUES ('RWF', '646','Rwanda Franc','0');
INSERT INTO currencies(alpha3, numeric4217, name, symbol, minor) VALUES ('SAR', '682','Saudi Riyal','2');
INSERT INTO currencies(alpha3, numeric4217, name, symbol, minor) VALUES ('SBD', '090','Solomon Islands Dollar','2');
INSERT INTO currencies(alpha3, numeric4217, name, symbol, minor) VALUES ('SCR', '690','Seychelles Rupee','2');
INSERT INTO currencies(alpha3, numeric4217, name, symbol, minor) VALUES ('SDG', '938','Sudanese Pound','2');
INSERT INTO currencies(alpha3, numeric4217, name, symbol, minor) VALUES ('SEK', '752','Swedish Krona','2');
INSERT INTO currencies(alpha3, numeric4217, name, symbol, minor) VALUES ('SGD', '702','Singapore Dollar','2');
INSERT INTO currencies(alpha3, numeric4217, name, symbol, minor) VALUES ('SHP', '654','Saint Helena Pound','2');
INSERT INTO currencies(alpha3, numeric4217, name, symbol, minor) VALUES ('SLL', '694','Leone','2');
INSERT INTO currencies(alpha3, numeric4217, name, symbol, minor) VALUES ('SOS', '706','Somali Shilling','2');
INSERT INTO currencies(alpha3, numeric4217, name, symbol, minor) VALUES ('SRD', '968','Surinam Dollar','2');
INSERT INTO currencies(alpha3, numeric4217, name, symbol, minor) VALUES ('SSP', '728','South Sudanese Pound','2');
INSERT INTO currencies(alpha3, numeric4217, name, symbol, minor) VALUES ('STD', '678','Dobra','2');
INSERT INTO currencies(alpha3, numeric4217, name, symbol, minor) VALUES ('SVC', '222','El Salvador Colon','2');
INSERT INTO currencies(alpha3, numeric4217, name, symbol, minor) VALUES ('SYP', '760','Syrian Pound','2');
INSERT INTO currencies(alpha3, numeric4217, name, symbol, minor) VALUES ('SZL', '748','Lilangeni','2');
INSERT INTO currencies(alpha3, numeric4217, name, symbol, minor) VALUES ('THB', '764','Baht','2');
INSERT INTO currencies(alpha3, numeric4217, name, symbol, minor) VALUES ('TJS', '972','Somoni','2');
INSERT INTO currencies(alpha3, numeric4217, name, symbol, minor) VALUES ('TMT', '934','Turkmenistan New Manat','2');
INSERT INTO currencies(alpha3, numeric4217, name, symbol, minor) VALUES ('TND', '788','Tunisian Dinar','3');
INSERT INTO currencies(alpha3, numeric4217, name, symbol, minor) VALUES ('TOP', '776','Pa’anga','2');
INSERT INTO currencies(alpha3, numeric4217, name, symbol, minor) VALUES ('TRY', '949','Turkish Lira','2');
INSERT INTO currencies(alpha3, numeric4217, name, symbol, minor) VALUES ('TTD', '780','Trinidad and Tobago Dollar','2');
INSERT INTO currencies(alpha3, numeric4217, name, symbol, minor) VALUES ('TWD', '901','New Taiwan Dollar','2');
INSERT INTO currencies(alpha3, numeric4217, name, symbol, minor) VALUES ('TZS', '834','Tanzanian Shilling','2');
INSERT INTO currencies(alpha3, numeric4217, name, symbol, minor) VALUES ('UAH', '980','Hryvnia','2');
INSERT INTO currencies(alpha3, numeric4217, name, symbol, minor) VALUES ('UGX', '800','Uganda Shilling','2');
INSERT INTO currencies(alpha3, numeric4217, name, symbol, minor) VALUES ('USD', '840','US Dollar','2');
INSERT INTO currencies(alpha3, numeric4217, name, symbol, minor) VALUES ('USN', '997','US Dollar (Next day)','2');
INSERT INTO currencies(alpha3, numeric4217, name, symbol, minor) VALUES ('USS', '998','US Dollar (Same day)','2');
INSERT INTO currencies(alpha3, numeric4217, name, symbol, minor) VALUES ('UYI', '940','Uruguay Peso en Unidades Indexadas (URUIURUI)','0');
INSERT INTO currencies(alpha3, numeric4217, name, symbol, minor) VALUES ('UYU', '858','Peso Uruguayo','2');
INSERT INTO currencies(alpha3, numeric4217, name, symbol, minor) VALUES ('UZS', '860','Uzbekistan Sum','2');
INSERT INTO currencies(alpha3, numeric4217, name, symbol, minor) VALUES ('VEF', '937','Bolivar ','2');
INSERT INTO currencies(alpha3, numeric4217, name, symbol, minor) VALUES ('VND', '704','Dong','0');
INSERT INTO currencies(alpha3, numeric4217, name, symbol, minor) VALUES ('VUV', '548','Vatu','0');
INSERT INTO currencies(alpha3, numeric4217, name, symbol, minor) VALUES ('WST', '882','Tala','2');
INSERT INTO currencies(alpha3, numeric4217, name, symbol, minor) VALUES ('XAF', '950','CFA Franc BEAC','0');
INSERT INTO currencies(alpha3, numeric4217, name, symbol, minor) VALUES ('XAG', '961','Silver','-');
INSERT INTO currencies(alpha3, numeric4217, name, symbol, minor) VALUES ('XAU', '959','Gold','-');
INSERT INTO currencies(alpha3, numeric4217, name, symbol, minor) VALUES ('XBA', '955','Bond Markets Unit European Composite Unit (EURCO)','-');
INSERT INTO currencies(alpha3, numeric4217, name, symbol, minor) VALUES ('XBB', '956','Bond Markets Unit European Monetary Unit (E.M.U.-6)','-');
INSERT INTO currencies(alpha3, numeric4217, name, symbol, minor) VALUES ('XBC', '957','Bond Markets Unit European Unit of Account 9 (E.U.A.-9)','-');
INSERT INTO currencies(alpha3, numeric4217, name, symbol, minor) VALUES ('XBD', '958','Bond Markets Unit European Unit of Account 17 (E.U.A.-17)','-');
INSERT INTO currencies(alpha3, numeric4217, name, symbol, minor) VALUES ('XCD', '951','East Caribbean Dollar','2');
INSERT INTO currencies(alpha3, numeric4217, name, symbol, minor) VALUES ('XDR', '960','SDR (Special Drawing Right)','-');
INSERT INTO currencies(alpha3, numeric4217, name, symbol, minor) VALUES ('XFU', 'Nil','UIC-Franc','-');
INSERT INTO currencies(alpha3, numeric4217, name, symbol, minor) VALUES ('XOF', '952','CFA Franc BCEAO','0');
INSERT INTO currencies(alpha3, numeric4217, name, symbol, minor) VALUES ('XPD', '964','Palladium','-');
INSERT INTO currencies(alpha3, numeric4217, name, symbol, minor) VALUES ('XPF', '953','CFP Franc','0');
INSERT INTO currencies(alpha3, numeric4217, name, symbol, minor) VALUES ('XPT', '962','Platinum','-');
INSERT INTO currencies(alpha3, numeric4217, name, symbol, minor) VALUES ('XSU', '994','Sucre','-');
INSERT INTO currencies(alpha3, numeric4217, name, symbol, minor) VALUES ('XTS', '963','Codes specifically reserved for testing purposes','-');
INSERT INTO currencies(alpha3, numeric4217, name, symbol, minor) VALUES ('XUA', '965','ADB Unit of Account','-');
INSERT INTO currencies(alpha3, numeric4217, name, symbol, minor) VALUES ('XXX', '999','The codes assigned for transactions where no currency is involved','-');
INSERT INTO currencies(alpha3, numeric4217, name, symbol, minor) VALUES ('YER', '886','Yemeni Rial','2');
INSERT INTO currencies(alpha3, numeric4217, name, symbol, minor) VALUES ('ZAR', '710','Rand','2');
INSERT INTO currencies(alpha3, numeric4217, name, symbol, minor) VALUES ('ZMW', '967','Zambian Kwacha','2');
INSERT INTO currencies(alpha3, numeric4217, name, symbol, minor) VALUES ('ZWL', '932','Zimbabwe Dollar','2');
